<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"设计师管理",
                        "menuJump":"列表",
                        "tableName":"shejishi"
                    }
                ],
                "menu":"设计师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"施工方管理",
                        "menuJump":"列表",
                        "tableName":"shiguongfang"
                    }
                ],
                "menu":"施工方管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"图纸信息管理",
                        "menuJump":"列表",
                        "tableName":"tuzhi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"图纸信息交流管理",
                        "menuJump":"列表",
                        "tableName":"tuzhiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"图纸信息收藏管理",
                        "menuJump":"列表",
                        "tableName":"tuzhiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"图纸信息订单管理",
                        "menuJump":"列表",
                        "tableName":"tuzhiOrder"
                    }
                ],
                "menu":"图纸信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"已接订单管理",
			            "menuJump":"列表",
			            "tableName":"dingdan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"已接订单交流管理",
			            "menuJump":"列表",
			            "tableName":"dingdanLiuyan"
			        }
			    ],
			    "menu":"已接订单管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"订单状态管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryOrder"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryTuzhi"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
            
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息交流管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息订单管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiOrder"
	                }
	            ],
	            "menu":"图纸信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"图纸信息管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"图纸信息交流管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息订单管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiOrder"
	                }
	            ],
	            "menu":"图纸信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改"
			            ],
			            "menu":"已接订单交流管理",
			            "menuJump":"列表",
			            "tableName":"dingdanLiuyan"
			        }
			    ],
			    "menu":"已接订单交流管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"设计师",
	    "tableName":"shejishi"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"图纸信息管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "接单"
	                    ],
	                    "menu":"订单管理",
	                    "menuJump":"列表",
	                    "tableName":"tuzhiOrder"
	                }
	            ],
	            "menu":"图纸信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "交流"
			            ],
			            "menu":"已接订单管理",
			            "menuJump":"列表",
			            "tableName":"dingdan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"已接订单交流管理",
			            "menuJump":"列表",
			            "tableName":"dingdanLiuyan"
			        }
			    ],
			    "menu":"已接订单管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	        
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"施工方",
	    "tableName":"shigongfang"
	}
];

var hasMessage = '';
